// Câu 3: Sinh prompt tối ưu để dán vào Google AI Studio → Build (aistudio.google.com/apps)
const { chatJSON } = require('./openai');

const str = { type: 'string' };
const obj = (properties) => ({ type: 'object', additionalProperties: false, properties, required: Object.keys(properties) });

const SCHEMA = obj({
  app_name: str,
  one_line_vi: str,
  prompt: str,
  fix_prompts: { type: 'array', items: str },
  demo_script_vi: { type: 'array', items: str },
});

const SYSTEM = `You write a single, complete build prompt for Google AI Studio "Build" mode (vibe-coding: it generates a React + TypeScript web app that can call the Gemini API; the GEMINI API key is configured automatically — the app must NOT ask the user for an API key).
Goal: a polished LANGUAGE-LEARNING app that works on the FIRST generation, for a university AI exam.
The prompt (field "prompt", written in ENGLISH) must specify:
1. App name, purpose, target language and learner's native language; ALL UI text in the learner's language.
2. 4–6 concrete features as numbered sections, each with exact behavior. Always include: (a) AI vocabulary/flashcards by topic generated by Gemini (word, IPA, meaning, example sentence), (b) pronunciation: "listen" button using the browser Web Speech API speechSynthesis with the correct lang code, and speaking practice via SpeechRecognition with a similarity score (graceful fallback if unsupported), (c) AI conversation/role-play chat tutor that corrects mistakes gently, (d) auto-generated quiz (multiple choice) with score, (e) progress tracking saved in localStorage (streak, words learned, quiz scores). Add any feature the exam requires.
3. Gemini usage: use the @google/genai SDK with model "gemini-2.5-flash" (or the default model AI Studio suggests), request JSON output with responseSchema for structured data, show loading states and friendly error messages.
4. UI/UX: modern, clean, responsive (mobile + desktop), tab or sidebar navigation, card layout, soft colors, large readable fonts, icons, empty states, subtle animations. Single-page app, no login, no backend other than Gemini.
5. Quality rules: no placeholder/lorem text, every button works, no API key input field, handle JSON parse errors, keep code in well-organized components.
Keep the prompt 350–650 words, well-structured with headings and bullet points.
"fix_prompts": 4 short ENGLISH follow-up prompts the student can paste into the AI Studio chat if something breaks (e.g. speech not working, JSON error, UI not in Vietnamese, make it prettier).
"demo_script_vi": 4–6 bước ngắn (tiếng Việt) để thí sinh demo app cho giám khảo.
"one_line_vi": 1 câu tiếng Việt mô tả app.`;

async function solveQ3(a, log) {
  log('Câu 3: soạn prompt cho Google AI Studio…');
  const q = a.q3;
  const text = `Exam requirements (Vietnamese, may be partial):
- Target language to learn: ${q.target_language || 'Tiếng Anh'}
- Learner native language / UI language: ${q.learner_language || 'Tiếng Việt'}
- Suggested app name: ${q.app_name || '(you choose a catchy name)'}
- Features required by exam: ${(q.features || []).join('; ') || '(none specified)'}
- Other requirements: ${(q.requirements || []).join('; ') || '(none)'}`;
  const r = await chatJSON({ system: SYSTEM, content: [{ type: 'text', text }], schema: SCHEMA, name: 'aistudio_prompt' });
  return r;
}

module.exports = { solveQ3 };
